server:
  port: 8002

spring:
#服务名称
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
        # git仓库地址
          uri: https://gitee.com/ServiceGalaxy/spring-cloud-config.git
          # git 用户名
          username: ServiceGalaxy
          # git 密码
          password: lsj19970911
#          在搜索在git上的目录(仓库的名称)
          search-paths: SpringCloud-Config
#          读取分支
          default-label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

