server:
  port: 8002

spring:
#服务名称
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ServiceGalaxy/spring-cloud-config.git
          username: ServiceGalaxy
          password: lsj19970911
#          在搜索在git上的目录(仓库的名称)
          search-paths: SpringCloud-Config
#          读取分支
          default-label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/ServiceGalaxy/spring-cloud-config.git
#          username: ServiceGalaxy
#          password: lsj19970911

